### ISSUE TITLE
Add spacing values to larva-tokens

### ISSUE THREAD

**Issue by laras126** [penske-media-corp/pmc-larva#186]
The designers are adding a spacing scale to their style guide. We need to have corresponding tokens for those values that can be configured in larva-tokens and output to the styleguide. 

I proposed keeping the naming the same for the token-based values:

* spacer-025
* spacer-050
* spacer-075
* spacer-1
* spacer-125
* spacer-150
* spacer-175
* spacer-2

**Comment by asannad** [comment]
Can we make em consistent like spacer-1 should be spacer-100?

**Comment by curtisbelt** [comment]
If implemented, Tailwind would supersede this issue - see #187

**Comment by laras126** [comment]
This was added in PR #202 - @asannad that is a good suggestion and I wish I saw this before I did it :( That said, there will be a push in the future to update existing utilities and that will be a good time to make naming improvements. I created issue  #248 to track this.
